import json
import os
import openpyxl
from openpyxl.styles import Font, Alignment, PatternFill, Border, Side
from openpyxl.utils import get_column_letter

def generate_excel_report(enriched_sbom_path, output_excel_path):
    print(f"Reading enriched SBOM from {enriched_sbom_path}...")
    if not os.path.exists(enriched_sbom_path):
        print(f"Error: Enriched SBOM file not found at {enriched_sbom_path}")
        return False
        
    with open(enriched_sbom_path, 'r', encoding='utf-8') as f:
        sbom = json.load(f)
        
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "SBOM Report"
    
    # Enable grid lines
    ws.views.sheetView[0].showGridLines = True
    
    # Design colors (Slate Blue Palette)
    header_fill = PatternFill(start_color="1F4E78", end_color="1F4E78", fill_type="solid")
    header_font = Font(name="Segoe UI", size=11, bold=True, color="FFFFFF")
    
    title_font = Font(name="Segoe UI", size=16, bold=True, color="1F4E78")
    meta_font = Font(name="Segoe UI", size=9, italic=True, color="595959")
    
    regular_font = Font(name="Segoe UI", size=10, color="000000")
    bold_regular_font = Font(name="Segoe UI", size=10, bold=True, color="000000")
    
    # Criticality Fills
    criticality_fills = {
        "critical": PatternFill(start_color="FFC7CE", end_color="FFC7CE", fill_type="solid"), # Light Red
        "high": PatternFill(start_color="FFEB9C", end_color="FFEB9C", fill_type="solid"),     # Light Yellow
        "medium": PatternFill(start_color="E2EFDA", end_color="E2EFDA", fill_type="solid"),   # Light Green
        "low": PatternFill(start_color="F2F2F2", end_color="F2F2F2", fill_type="solid")       # Light Gray
    }
    
    border_side = Side(border_style="thin", color="D9D9D9")
    cell_border = Border(left=border_side, right=border_side, top=border_side, bottom=border_side)
    
    # Write Title block
    ws.cell(row=1, column=1, value="Software Bill of Materials (SBOM) Compliance Report").font = title_font
    
    metadata = sbom.get('metadata', {})
    author = metadata.get('authors', [{}])[0].get('name', 'Unknown')
    timestamp = metadata.get('timestamp', 'Unknown')
    
    ws.cell(row=2, column=1, value=f"Generated By: {author}  |  Timestamp: {timestamp}").font = meta_font
    ws.row_dimensions[1].height = 25
    ws.row_dimensions[2].height = 18
    
    # Define Column Headers matching the 21 attributes
    headers = [
        "Sr No", "Component Name", "Version", "Description", "Supplier", 
        "License", "Origin", "Dependencies", "Vulnerabilities", "Patch Status", 
        "Release Date", "EOL Date", "Criticality", "Usage Restrictions", "Checksums/Hashes", 
        "Comments", "Author of SBOM Data", "Timestamp", "Executable", "Archive", 
        "Structured Format", "Unique Identifier (PURL)"
    ]
    
    header_row = 4
    ws.row_dimensions[header_row].height = 28
    
    for col_idx, header in enumerate(headers, 1):
        cell = ws.cell(row=header_row, column=col_idx, value=header)
        cell.fill = header_fill
        cell.font = header_font
        cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
        cell.border = cell_border
        
    components = sbom.get('components', [])
    vulnerabilities = sbom.get('vulnerabilities', [])
    
    # Map dependencies for quick lookup
    deps = sbom.get('dependencies', [])
    dep_map = {d.get('ref'): d.get('dependsOn', []) for d in deps}
    
    start_data_row = 5
    for idx, comp in enumerate(components, 1):
        row_idx = start_data_row + idx - 1
        ws.row_dimensions[row_idx].height = 20
        
        name = comp.get('name', '')
        version = comp.get('version', '')
        desc = comp.get('description', '')
        supplier = comp.get('supplier', {}).get('name', '')
        license_str = ', '.join([l.get('license', {}).get('name', '') for l in comp.get('licenses', [])])
        purl = comp.get('purl', '')
        
        # Read custom properties
        properties = comp.get('properties', [])
        prop_map = {p.get('name'): p.get('value') for p in properties}
        
        origin = prop_map.get('origin', 'open-source')
        patch_status = prop_map.get('patch_status', 'up-to-date')
        release_date = prop_map.get('release_date', '')
        eol_date = prop_map.get('eol_date', '')
        criticality = prop_map.get('criticality', 'medium').lower()
        usage_restrictions = prop_map.get('usage_restrictions', 'None')
        comments = prop_map.get('comments', '')
        executable = prop_map.get('executable', 'false')
        archive = prop_map.get('archive', 'true')
        structured = prop_map.get('structured', '')
        
        # Resolve hashes string
        hashes_str = ', '.join([f"{h.get('alg')}:{h.get('content')[:12]}..." for h in comp.get('hashes', [])])
        
        # Resolve dependencies names/versions
        bom_ref = comp.get('bom-ref') or purl
        child_refs = dep_map.get(bom_ref, [])
        children = []
        for ref in child_refs:
            # Find name of the child component
            child_name = ref.split('/')[-1].split('@')[0] if '/' in ref else ref
            children.append(child_name)
        dependencies_str = ', '.join(children) if children else "None"
        
        # Resolve vulnerabilities for this component
        comp_vulns = []
        for v in vulnerabilities:
            affects = v.get('affects', [])
            if any(a.get('ref') == bom_ref for a in affects):
                comp_vulns.append(v.get('id', ''))
        vulns_str = ', '.join(comp_vulns) if comp_vulns else "None"
        
        # Columns values
        row_values = [
            idx,                                # Sr No
            name,                               # Component Name
            version,                            # Version
            desc,                               # Description
            supplier,                           # Supplier
            license_str,                        # License
            origin,                             # Origin
            dependencies_str,                   # Dependencies
            vulns_str,                          # Vulnerabilities
            patch_status,                       # Patch Status
            release_date,                       # Release Date
            eol_date,                           # EOL Date
            criticality.upper(),                # Criticality
            usage_restrictions,                 # Usage Restrictions
            hashes_str,                         # Checksums/Hashes
            comments,                           # Comments
            author,                             # Author of SBOM Data
            timestamp,                          # Timestamp
            executable,                         # Executable
            archive,                            # Archive
            structured,                         # Structured Format
            purl                                # Unique Identifier (PURL)
        ]
        
        # Write to cells
        for col_idx, val in enumerate(row_values, 1):
            cell = ws.cell(row=row_idx, column=col_idx, value=val)
            cell.font = regular_font
            cell.alignment = Alignment(vertical="center")
            cell.border = cell_border
            
            # Left align strings, center numeric/dates
            if col_idx in [1, 3, 10, 11, 12, 13, 17, 18, 19, 20]:
                cell.alignment = Alignment(horizontal="center", vertical="center")
                
            # Colored criticality highlights
            if col_idx == 13: # Criticality column
                cell.font = bold_regular_font
                fill = criticality_fills.get(criticality)
                if fill:
                    cell.fill = fill
                    
    # Auto-adjust column widths for perfect layout presentation
    for col in ws.columns:
        # Ignore Title rows for width calculation
        max_len = 0
        col_letter = get_column_letter(col[0].column)
        
        for cell in col[3:]: # start from header row
            val_str = str(cell.value or '')
            if len(val_str) > max_len:
                max_len = len(val_str)
                
        # Limit max column width to prevent extreme wide descriptions
        calculated_width = max(max_len + 4, 12)
        if calculated_width > 50:
            calculated_width = 50
        ws.column_dimensions[col_letter].width = calculated_width
        
    print(f"Saving Excel report to {output_excel_path}...")
    os.makedirs(os.path.dirname(os.path.abspath(output_excel_path)), exist_ok=True)
    wb.save(output_excel_path)
    print("[+] Excel report generated successfully.")
    return True

if __name__ == "__main__":
    import sys
    base_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(base_dir)
    
    enriched_path = os.path.join(project_root, "sbom_output", "restricted", "sbom_enriched.json")
    output_path = os.path.join(project_root, "sbom_output", "public", "sbom_report.xlsx")
    
    if len(sys.argv) > 1:
        enriched_path = sys.argv[1]
    if len(sys.argv) > 2:
        output_path = sys.argv[2]
        
    generate_excel_report(enriched_path, output_path)
